### ISSUE TITLE
cannot get past the install.php and login screen

### ISSUE THREAD

**Issue by aniston** [aswzen/MonoLead#1]
Hello, I've been trying to use the application on a simple windows Z-WAMP setup as well an external hosted LAMP but cannot get/see a confirmation after the initial install.php screen details.

After submitting correct details in teh install.php section via web browser the returned page only has "MonoLead Setup" as a heading but no other data in there as a confiration of what went right or wrong, so i tired to give wrong credentials and still it hangs there at the heading. I don't get PHP errore (running with E_ALL) , anyplace I can check ?

regards,
Aniston

**Comment by aswzen** [comment]
could you tell me are you trying this app on live/production or just want to try because this app is still in pre alpha and unstable..

can you show me the content of a file named config.php inside directory
yourwebserverroot\MonoLead\application\config

thanks

**Comment by aswzen** [comment]
its fixed now #2e653d8742d5fbc33ee35bf3658f02289ac66dcd

**Comment by aswzen** [comment]
its fixed now
